### ISSUE TITLE
No longer in Google Play?

### ISSUE THREAD

**Issue by nightwatchcyber** [ViliusKraujutis/AndroidBroadcastsMonitor#12]
Hi - it looks like this app is no longer listed in the Google Play store:
https://viliuskraujutis.github.io/AndroidBroadcastsMonitor/

Do you have an APK that can be sideloaded instead?

Thanks!

**Comment by vilius-kraujutis-ht** [comment]
Hm, that's strange. It should still have been published. I'll have to look into why it's gone from Google Play. Maybe I've missed some email with some new requirement. Thanks for letting me know about this issue.

**Comment by ViliusKraujutis** [comment]
Apparently, Google Play Store wanted to have app rating, some additional translations/descriptions, featured graphics etc... so I've updated that and resubmitted the app.

App should reappear here: https://play.google.com/store/apps/details?id=lt.andro.broadcastlogger

**Comment by ViliusKraujutis** [comment]
@nightwatchcyber could you please close this issue once the app appears on Google Play?

**Comment by nightwatchcyber** [comment]
Thank you for fixing this, it is now live on Google Play
