### ISSUE TITLE
can  i detect that any app is going to be started using its home icon i need package name of that app ? 

### ISSUE THREAD

**Issue by engr-erum** [ViliusKraujutis/AndroidBroadcastsMonitor#4]
is there any broadcast reciveer so that when user starts any app i can get the package name of that app using broadcast reciever ?

**Comment by ViliusKraujutis** [comment]
@erumhannan did you find a solution? Is this still actual?

**Comment by ViliusKraujutis** [comment]
I'm not aware about such possibility. Closing as there's no updates from question author.
